# Generated by Django 5.0.1 on 2024-02-16 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LicencePlate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.CharField(max_length=15)),
                ('identified', models.BooleanField(default=False)),
                ('initial_image', models.ImageField(upload_to='initial')),
                ('plate_image', models.ImageField(upload_to='plates')),
                ('processed_image', models.ImageField(upload_to='processed_image')),
            ],
        ),
    ]
